export const RECEIVE_LAUNCHES = 'RECEIVE_LAUNCHES';
export const REQUEST_LAUNCHES = 'REQUEST_LAUNCHES';
export const REQUEST_LAUNCHES_FAILURE = 'REQUEST_LAUNCHES_FAILURE';
export const REQUEST_ROCKETS = 'REQUEST_ROCKETS';
export const RECEIVE_ROCKETS = 'RECEIVE_ROCKETS';
export const REQUEST_ROCKETS_FAILURE = 'REQUEST_ROCKETS_FAILURE';
